// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsChBk8QJZPPNMgr_k9fuxPEogqLXtDA0',
    appId: '1:883573169106:web:e333e530119d71f981c60b',
    messagingSenderId: '883573169106',
    projectId: 'lotterie-de-l-etat-haitien',
    authDomain: 'lotterie-de-l-etat-haitien.firebaseapp.com',
    storageBucket: 'lotterie-de-l-etat-haitien.firebasestorage.app',
    measurementId: 'G-N56EK36JQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHqcDgQvOI3y-nevU3cssrNQScTNu2NBc',
    appId: '1:969896261161:android:561b38b2b2dc3e82268e38',
    messagingSenderId: '969896261161',
    projectId: 'haiti-alert',
    storageBucket: 'haiti-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRg6JZJmfjn55LKjHsFdK9rPw7yAtQnE',
    appId: '1:969896261161:ios:4a717f22d7239010268e38',
    messagingSenderId: '969896261161',
    projectId: 'haiti-alert',
    storageBucket: 'haiti-alert.firebasestorage.app',
    iosBundleId: 'ht.ehaiti.alert',
  );

}